# Data Manipulation with Pandas

    Introducing Pandas Objects
    Data Indexing and Selection
    Operating on Data in Pandas
    Handling Missing Data

In [2]:
import numpy as np
import pandas as pd

## Introducing Pandas Objects

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices. 

A Pandas **Series** is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.values #this is a NumPy array

array([ 0.25,  0.5 ,  0.75,  1.  ])

The **index** is an array-like object of type **pd.Index**.

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

We can still use the square bracket notation for accessing data.

In [6]:
data[1]

0.5

In [7]:
data[1:3]

1    0.50
2    0.75
dtype: float64

## Data Indexing and Selection

From what we've seen so far, it may look like the Series object is basically interchangeable with a one-dimensional NumPy array. The essential difference is the presence of the index: while the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an **explicitly defined index** associated with the values.

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd']) #doesn't need to be ints
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

0.5

The Pandas Series object is similar to Python's dictionaries, they both map keys to value. In a dictionary these keys and values are arbitrary, while Pandas maps typed keys to typed values.

The Series-as-dictionary analogy can be made even more clear by constructing a Series object directly from a Python dictionary:

In [11]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

By default, a Series will be created where the index is drawn from the sorted keys.

In [12]:
population['California']

38332521

In [13]:
population['California':'Illinois'] #can't do this with a dict!

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

Creating a Pandas Series follows some version of;

pd.Series(data, index=index)

where index is an optional argument, and data can be one of many entities.

In [16]:
print(pd.Series([2, 4, 6])) #from list with default index
print(pd.Series(5, index=[100, 200, 300])) #from scalar, fills to match index
print(pd.Series({2:'a', 1:'b', 3:'c'})) #from dict, index is keys
print(pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])) 
#index is choosen, only take vals from dict with specified keys


0    2
1    4
2    6
dtype: int64
100    5
200    5
300    5
dtype: int64
1    b
2    a
3    c
dtype: object
3    c
2    a
dtype: object


If a Series is an analog of a one-dimensional array with flexible indices, a **DataFrame** is an analog of a two-dimensional array with both flexible row indices and flexible column names.

In [18]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

Now that we have this along with the population Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [19]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

Like the Series object, the DataFrame has an index attribute that gives access to the index labels:

In [20]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [22]:
states.columns

Index(['area', 'population'], dtype='object')

In [23]:
states['area'] #access area column

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

A DataFrame is a collection of Series objects, and a single-column DataFrame can be constructed from a single Series:

In [24]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193

Any list of dictionaries can be made into a DataFrame. We'll use a simple list comprehension to create some data:

In [26]:
data = [{'a':i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e., "not a number") values:

In [27]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

Given a two-dimensional array of data, we can create a DataFrame with any specified column and index names. If omitted, an integer index will be used for each:

In [28]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.775247  0.689695
b  0.552289  0.214928
c  0.666851  0.480478

Pandas DataFrame operates much like a structured array, and can be created directly from one:

In [29]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0,  0.), (0,  0.), (0,  0.)], 
      dtype=[('A', '<i8'), ('B', '<f8')])

In [30]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

The **Index** object is an interesting structure in itself, and it can be thought of either as an immutable array or as an ordered set (technically a multi-set, as Index objects may contain repeated values).

In [31]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

The Index in many ways operates like an array. For example, we can use standard Python indexing notation to retrieve values or slices:

In [32]:
ind[1]

3

In [33]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [34]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


One difference between Index objects and NumPy arrays is that indices are immutable–that is, they cannot be modified via the normal means:

In [35]:
ind[1] = 0

TypeError: Index does not support mutable operations

## Operating on Data in Pandas

Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic. The Index object follows many of the conventions used by Python's built-in set data structure, so that unions, intersections, differences, and other combinations can be computed in a familiar way:

In [36]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [37]:
indA & indB #intersection

Int64Index([3, 5, 7], dtype='int64')

In [39]:
indA | indB #union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [40]:
indA ^ indB #symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

We can use dictionary-like Python expressions and methods to examine the keys/indices and values:

In [41]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [42]:
data['b']

0.5

In [43]:
'a' in data

True

In [44]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [45]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

You can extend a Series by assigning to a new index value:

In [46]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

**Slicing, masking, and indexing a Pandas Series object;**

In [47]:
data['a':'c'] #index slicing
#note: final index is included here, but won't be below

a    0.25
b    0.50
c    0.75
dtype: float64

In [51]:
data[0:2] #slicing by integer index
#see?! The final index is not included in the integer slice

a    0.25
b    0.50
dtype: float64

In [49]:
data[(data > 0.3) & (data < 0.8)] #masking

b    0.50
c    0.75
dtype: float64

In [50]:
data[['a', 'e']] #fancy indexing

a    0.25
e    1.25
dtype: float64

In [52]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [53]:
data[1] #explicit index

'a'

In [54]:
data[1:3] #implicit index

3    b
5    c
dtype: object

See, that's a little confusing!

Because of this potential confusion in the case of integer indexes, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes.

First, the **loc attribute** allows indexing and slicing that **always references the explicit index**:

In [55]:
data.loc[1]

'a'

In [56]:
data.loc[1:3]

1    a
3    b
dtype: object

The **iloc attribute** allows indexing and slicing that **always references the implicit Python-style index**:

In [57]:
data.iloc[1]

'b'

In [58]:
data.iloc[1:3]

3    b
5    c
dtype: object

One guiding principle of Python code is that **"explicit is better than implicit."** 

The explicit nature of loc and iloc make them very useful in maintaining clean and readable code; especially in the case of integer indexes, I recommend using these both to make code easier to read and understand, and to prevent subtle bugs due to the mixed indexing/slicing convention.

In [59]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

The individual Series that make up the columns of the DataFrame can be accessed via dictionary-style indexing of the column name:

In [60]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [61]:
data.area #won't work if column name has space

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [62]:
data.area is data['area'] #these are the same object

True

Though this is a useful shorthand, keep in mind that it does not work for all cases! For example, if the column names are not strings, or if the column names conflict with methods of the DataFrame, this attribute-style access is not possible.

In particular, you should avoid the temptation to try column assignment via attribute (i.e., use data['pop'] = z rather than data.pop = z).

Dictionary-style syntax can also be used to modify the object, in this case adding a new column:

In [63]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [64]:
data.values

array([[  4.23967000e+05,   3.83325210e+07,   9.04139261e+01],
       [  1.70312000e+05,   1.95528600e+07,   1.14806121e+02],
       [  1.49995000e+05,   1.28821350e+07,   8.58837628e+01],
       [  1.41297000e+05,   1.96511270e+07,   1.39076746e+02],
       [  6.95662000e+05,   2.64481930e+07,   3.80187404e+01]])

We can **transpose** the full DataFrame to swap rows and columns:

In [65]:
data.T

California       Florida      Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01

Passing a single index to an array accesses a row:

In [66]:
data.values[0]

array([  4.23967000e+05,   3.83325210e+07,   9.04139261e+01])

Passing a single "index" to a DataFrame accesses a column:

In [68]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

Thus for array-style indexing, we need another convention. Here Pandas again uses the loc, iloc, and ix indexers mentioned earlier. 

Using the **iloc** indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the DataFrame index and column labels are maintained in the result:

In [69]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

Similarly, using the **loc** indexer we can index the underlying data in an array-like style but using the explicit index and column names:

In [70]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [72]:
data.loc[data.density > 100, ['pop', 'density']] #masking with loc

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746

In [73]:
data.iloc[0, 2] = 90 #modify value with iloc
data

area       pop     density
California  423967  38332521   90.000000
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

First, while indexing refers to columns, slicing refers to rows:

In [78]:
%xmode Plain

data['Florida']

Exception reporting mode: Plain


KeyError: 'Florida'

In [74]:
data['Florida':'Illinois'] #remember data['Florida'] is an error

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [75]:
data[1:3]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [79]:
data[data.density > 100]

area       pop     density
Florida   170312  19552860  114.806121
New York  141297  19651127  139.076746

ecause Pandas is designed to work with NumPy, any NumPy ufunc will work on Pandas Series and DataFrame objects.

In [80]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [81]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [82]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [83]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [85]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [86]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

The resulting array contains the union of indices of the two input arrays, which could be determined using standard Python set arithmetic on these indices:

In [87]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

Any item for which one or the other does not have an entry is marked with NaN, or "Not a Number," which is how Pandas marks missing data.

If using NaN values is not the desired behavior, the fill value can be modified using appropriate object methods in place of the operators. For example, calling A.add(B) is equivalent to calling A + B, but allows optional explicit specification of the fill value for any elements in A or B that might be missing:

In [88]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [89]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [90]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [91]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [92]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

We can use the associated object's arithmetic method and pass any desired fill_value to be used in place of missing entries. Here we'll fill with the mean of all values in A (computed by first stacking the rows of A):

In [93]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [94]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [96]:
A - A[0] #difference between A and it's first row

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [97]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0] #difference between df and it's first row

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

If you would instead like to operate column-wise, you can use the object methods mentioned earlier, while specifying the axis keyword:

In [98]:
df.subtract(df['R'], axis = 0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [99]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int64

In [101]:
df - halfrow #automatically align indicies

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

This preservation and alignment of indices and columns means that operations on data in Pandas will always maintain the data context, which prevents the types of silly errors that might come up when working with heterogeneous and/or misaligned data in raw NumPy arrays.

## Handling Missing Data

The way in which Pandas handles missing values is constrained by its reliance on the NumPy package, which does not have a built-in notion of NA values for non-floating-point data types.

Pandas chose to use sentinels for missing data, and further chose to use two already-existing Python null values: the special floating-point NaN value, and the Python None object.

In [102]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

This dtype=object means that the best common type representation NumPy could infer for the contents of the array is that they are Python objects. While this kind of object array is useful for some purposes, any operations on the data will be done at the Python level, with much more overhead than the typically fast operations seen for arrays with native types:

In [103]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
66.8 ms ± 2.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

dtype = int
2.07 ms ± 320 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



The use of Python objects in an array also means that if you perform aggregations like sum() or min() across an array with a None value, you will generally get an error:

In [104]:
%xmode Plain
vals1.sum()

Exception reporting mode: Plain


TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

The other missing data representation, NaN (acronym for Not a Number), is different; it is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation:

In [105]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [106]:
1 + np.nan

nan

In [107]:
0 *  np.nan


nan

In [111]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

NumPy does provide some special aggregations that will ignore these missing values:

In [110]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

Keep in mind that NaN is specifically **a floating-point value**; there is no equivalent NaN value for integers, strings, or other types.

NaN and None both have their place, and Pandas is built to handle the two of them nearly interchangeably, converting between them where appropriate:

In [113]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

If there is no sentinel value, Pandas upcasts the object to accommodate the NA.

In [116]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [117]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

Pandas methods for dealing with None and Nan;

**isnull():** Generate a boolean mask indicating missing values

**notnull():** Opposite of isnull()

**dropna():** Return a filtered version of the data

**fillna():** Return a copy of the data with missing values filled or imputed

In [118]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [120]:
data[data.notnull()] #return the not null values

0        1
2    hello
dtype: object

In [121]:
data.dropna() #drops na values

0        1
2    hello
dtype: object

In [122]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [123]:
df.dropna() # drop all rows in which any null value is present

0    1  2
1  2.0  3.0  5

In [124]:
df.dropna(axis='columns') #drop columns with any null value

2
0  2
1  5
2  6

This drop good data too though. We want to drop column with *all* or *a majority* of null values. We can do this with the how or thresh parameters.

The defualt is how='any', this can be changed to how='all' to only drop rows/columns that are *all* null values.

In [125]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [126]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

Thresh sets the  minimum number of non-null values for the row/column to be kept

In [127]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [128]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

Sometimes you just want to replace the null values with a valid value.

In [129]:
data.fillna(0) #fills all nan with 0

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [130]:
data.fillna(method='ffill') #fills with previous value

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [131]:
data.fillna(method='bfill') #fills with next value

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [132]:
df.fillna(method='ffill', axis=1) #fill along cols using previous value

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

If a previous value is not available, it will remain NaN.

In [134]:
df = df.fillna(method='ffill', axis=1)
df = df.fillna(method='ffill', axis=0)

In [136]:
df

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  2.0  4.0  6.0  6.0